#!/bin/bash
sudo apt-get install python-pip -y
sudo apt-get install python-tk -y
sudo apt-get install python-imaging python-pil.imagetk -y
pip install cryptography
sudo pip install bcrypt
sudo pip install pynacl
sudo pip install paramiko
sudo pip install tkinter
sudo pip install python-xlib

sudo echo -e "#!/bin/bash\npython /opt/omadsconnect/omadsconnect.py " >> /usr/bin/omadsconnect
sudo chmod +x /usr/bin/omadsconnect

sudo echo -e  "[Desktop Entry]\nName=OmadsConnect\nType=Application\nExec=omadsconnect\nTerminal=false\nIcon=/opt/omadsconnect/images/logo.gif\nComment=Virtualization\nNoDisplay=false\nCategories=X-Internet" >> /usr/share/applications/omadsconnect.desktop

sudo desktop-file-install /usr/share/applications/omadsconnect.desktop

